// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQUAkjy0y0lobEmZQM1XZUIW33Sh2ErdA',
    appId: '1:203726031059:web:b531741da69b1dc2336c26',
    messagingSenderId: '203726031059',
    projectId: 'destination-app-d939a',
    authDomain: 'destination-app-d939a.firebaseapp.com',
    storageBucket: 'destination-app-d939a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvTqfoLq0M8BcM9y2sFvJNDEIEA-XBik',
    appId: '1:203726031059:android:e87d6f7c3b0762ca336c26',
    messagingSenderId: '203726031059',
    projectId: 'destination-app-d939a',
    storageBucket: 'destination-app-d939a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANx7GHh4mjF025qtTb36dcKyj3nlQ6W0s',
    appId: '1:203726031059:ios:905ce2aa3fc67c0a336c26',
    messagingSenderId: '203726031059',
    projectId: 'destination-app-d939a',
    storageBucket: 'destination-app-d939a.firebasestorage.app',
    iosBundleId: 'com.example.appTouristDestination',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANx7GHh4mjF025qtTb36dcKyj3nlQ6W0s',
    appId: '1:203726031059:ios:905ce2aa3fc67c0a336c26',
    messagingSenderId: '203726031059',
    projectId: 'destination-app-d939a',
    storageBucket: 'destination-app-d939a.firebasestorage.app',
    iosBundleId: 'com.example.appTouristDestination',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQUAkjy0y0lobEmZQM1XZUIW33Sh2ErdA',
    appId: '1:203726031059:web:8d3c8519931c378a336c26',
    messagingSenderId: '203726031059',
    projectId: 'destination-app-d939a',
    authDomain: 'destination-app-d939a.firebaseapp.com',
    storageBucket: 'destination-app-d939a.firebasestorage.app',
  );
}
